on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick@6
          brew install libgit2
          sudo ln -sf /opt/gfortran/SDK /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk
          sudo mkdir /opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/
          sudo ln -s /opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1 /opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            bioc::GENESIS
            any::rcmdcheck
          needs: |
            website
            coverage
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
